travis:
  secure:
    BINSTAR_TOKEN: vWOskoiUo2jhlG9vl8OIEK/HPE/5v8X89QlnDnWVMhLzqLONbsXNfgdbfQ/8YvBMCxC8zHPyQVcOXu+SzPzy3/ZnMqr8AayvALNK/+yZA6Oiv4Nc+7zeBGXJB2Rp28BvEcxxjTQN2tvMTG5T/YXAYsWNomdtiFyxiTJZxCLyk8ESpEQKMRS8F/yLj9zYBrYxy8gsOCmo/DzgXb+EBUKsQhdoZ/DZDN0BpwZj1P+nZAeuqd2Y2c/hdSII5dJL0Oui+IENNLE7CU3ocurQav8qyODZpvupuia0cruxbxB5oUtbvG1fFf3yRi3sE48w6I64+au4KB4STtnUH2ia8YqBTZC7ZCkWKQ7cw1AH8kRjSSKIKhQLTZr4HnvJhmTRX6+Iw8fqBQr7T2k1ZxLkLVrb1wxEPdGYABvQyKGLY2bjUD4v6i+OrNt6VbtzCQEyNxEWD+EIlkQ/+Kd7rJC0DwrQAqyZzqbA8fgE/IhVaEEF4I5GVaFY60YdMQUTMAkizXm0E1T+4hxfpNBaQ72aA9mfvYvY4FuO+9hnOKMkzF897UOLwTrjlYs4gYnr0bUKOuaA+40eEH83t2OWgpnaxX7R9Esyy14lK2k82+0LUlrfD0PtYn3Z97AWdsKgK6ytWwGSOyQ5LTPLYhjR8d+OHpkQU9w21xdEMZxQronA8779RCI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
